### ISSUE TITLE
xenomappability --mapped_test_data error.

### ISSUE THREAD

**Issue by fjrossello** [genomematt/xenomapper#4]
While running:
*xenomappability --mapped_test_data xenomapper/GRCh38_100_reads_GRCh38_specific.sam > GRCh38_100_reads_GRCh38_specific.wig*

Got following error:

*Traceback (most recent call last):
  File "/home/fernandr/biotools/bin/xenomappability", line 11, in <module>
    sys.exit(main())
  File "/home/fernandr/biotools/lib/python3.4/site-packages/xenomapper/mappability.py", line 302, in main
    single_end_mappability_from_sam(samfile=args.mapped_test_data)
  File "/home/fernandr/biotools/lib/python3.4/site-packages/xenomapper/mappability.py", line 183, in single_end_mappability_from_sam
    name_pos = int(name.split('_')[1])
ValueError: invalid literal for int() with base 10: 'KI270721v1'*

I guess it's related to chromosome names in reference. As suggested, I used:

**GCA_000001405.15_GRCh38_no_alt_analysis_set.fna**

**Comment by genomematt** [comment]
ok, I have never done this on the whole file before and there are names that already include underscores.
I have a fix for this, just need to write some proper tests.

Can you raise a bug on github “does not support chromosome names containing underscores” and I will push the fix later in the day.

Been spending my week getting the old house ready for sale and had a few issues like the bathroom tiles all falling off!

Regs,
matt

--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=

Dr Matthew Wakefield                      
http://bioinf.wehi.edu.au/~wakefield/ <http://bioinf.wehi.edu.au/~wakefield/>
Bioinformatics
Walter and Eliza Hall Institute
1G Royal Parade, Parkville, Vic 3052 Australia
matthew.wakefield@wehi.edu.au <mailto:matthew.wakefield@wehi.edu.au> 

Senior Research Fellow
Life Sciences Computation Centre
Victorian Life Sciences Computation Initiative
University of Melbourne, Parkville Campus
LAB-14, 700 Swanston St, Carlton VIC 3053, Australia
VLSCI, University of Melbourne
matthew.wakefield@unimelb.edu.au <mailto:matthew.wakefield@unimelb.edu.au>

Office Phone: +61 3 9345 2631     Mobile: +61 402 916 018
Skype Video: mjwakefield              GoogleTalk: MattJWakefield
Twitter & Github @genomematt     orcid.org/0000-0001-6624-4698 <http://orcid.org/0000-0001-6624-4698>

--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=

The information contained in this e-mail is confidential and is intended
solely for the addressee. If you are not the named addressee, you must not
disclose or use in any way the information in the e-mail. If you have
received this e-mail by mistake, please notify the sender immediately by
reply e-mail and delete this e-mail and destroy any printed copy.

> On 7 Jul 2015, at 6:35 pm, fjrossello <notifications@github.com> wrote:
> 
> While running:
> xenomappability --mapped_test_data xenomapper/GRCh38_100_reads_GRCh38_specific.sam > GRCh38_100_reads_GRCh38_specific.wig
> 
> Got following error:
> 
> Traceback (most recent call last):
> File "/home/fernandr/biotools/bin/xenomappability", line 11, in 
> sys.exit(main())
> File "/home/fernandr/biotools/lib/python3.4/site-packages/xenomapper/mappability.py", line 302, in main
> single_end_mappability_from_sam(samfile=args.mapped_test_data)
> File "/home/fernandr/biotools/lib/python3.4/site-packages/xenomapper/mappability.py", line 183, in single_end_mappability_from_sam
> name_pos = int(name.split('_')[1])
> ValueError: invalid literal for int() with base 10: 'KI270721v1'
> 
> I guess it's related to chromosome names in reference. As suggested, I used:
> 
> GCA_000001405.15_GRCh38_no_alt_analysis_set.fna
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/genomematt/xenomapper/issues/4>.
> 


______________________________________________________________________
The information in this email is confidential and intended solely for the addressee.
You must not disclose, forward, print or use it without the permission of the sender.
______________________________________________________________________

**Comment by fjrossello** [comment]
Hi Matt,
Done.

Feel sorry for you; I tend to think that moving houses it painful but I
imagine preparing a house for sale it's exponentially more difficult.
I am slowly but consistently progressing on this. The method I used for my
paper is super slow but I am getting there.
Keep in touch.

Cheers,

Fer

On 9 July 2015 at 10:46, Matthew Wakefield <notifications@github.com> wrote:

> ok, I have never done this on the whole file before and there are names
> that already include underscores.
> I have a fix for this, just need to write some proper tests.
>
> Can you raise a bug on github “does not support chromosome names
> containing underscores” and I will push the fix later in the day.
>
> Been spending my week getting the old house ready for sale and had a few
> issues like the bathroom tiles all falling off!
>
> Regs,
> matt
>
>
> --=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=
>
> Dr Matthew Wakefield
> http://bioinf.wehi.edu.au/~wakefield/ <
> http://bioinf.wehi.edu.au/~wakefield/>
> Bioinformatics
> Walter and Eliza Hall Institute
> 1G Royal Parade, Parkville, Vic 3052 Australia
> matthew.wakefield@wehi.edu.au <mailto:matthew.wakefield@wehi.edu.au>
>
> Senior Research Fellow
> Life Sciences Computation Centre
> Victorian Life Sciences Computation Initiative
> University of Melbourne, Parkville Campus
> LAB-14, 700 Swanston St, Carlton VIC 3053, Australia
> VLSCI, University of Melbourne
> matthew.wakefield@unimelb.edu.au <mailto:matthew.wakefield@unimelb.edu.au>
>
> Office Phone: +61 3 9345 2631 Mobile: +61 402 916 018
> Skype Video: mjwakefield GoogleTalk: MattJWakefield
> Twitter & Github @genomematt orcid.org/0000-0001-6624-4698 <
> http://orcid.org/0000-0001-6624-4698>
>
>
> --=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=
>
> The information contained in this e-mail is confidential and is intended
> solely for the addressee. If you are not the named addressee, you must not
> disclose or use in any way the information in the e-mail. If you have
> received this e-mail by mistake, please notify the sender immediately by
> reply e-mail and delete this e-mail and destroy any printed copy.
>
> > On 7 Jul 2015, at 6:35 pm, fjrossello <notifications@github.com> wrote:
> >
> > While running:
> > xenomappability --mapped_test_data
> xenomapper/GRCh38_100_reads_GRCh38_specific.sam >
> GRCh38_100_reads_GRCh38_specific.wig
> >
> > Got following error:
> >
> > Traceback (most recent call last):
> > File "/home/fernandr/biotools/bin/xenomappability", line 11, in
> > sys.exit(main())
> > File
> "/home/fernandr/biotools/lib/python3.4/site-packages/xenomapper/mappability.py",
> line 302, in main
> > single_end_mappability_from_sam(samfile=args.mapped_test_data)
> > File
> "/home/fernandr/biotools/lib/python3.4/site-packages/xenomapper/mappability.py",
> line 183, in single_end_mappability_from_sam
> > name_pos = int(name.split('_')[1])
> > ValueError: invalid literal for int() with base 10: 'KI270721v1'
> >
> > I guess it's related to chromosome names in reference. As suggested, I
> used:
> >
> > GCA_000001405.15_GRCh38_no_alt_analysis_set.fna
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/genomematt/xenomapper/issues/4>.
> >
>
>
> ______________________________________________________________________
> The information in this email is confidential and intended solely for the
> addressee.
> You must not disclose, forward, print or use it without the permission of
> the sender.
> ______________________________________________________________________
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/genomematt/xenomapper/issues/4#issuecomment-119772200>
> .
>



-- 

*Dr Fernando J. Rossello, PhDResearch Fellow*








*Department of Anatomy and Developmental BiologyAustralian Regenerative
Medicine InstituteLevel 3 Building 75Monash UniversityWellington
RoadClayton, Victoria 3800Australia*

*Ph: +61 (3) 9902 4762Email: fernando.rossello@monash.edu
<fernando.rossello@monash.edu>*

**Comment by genomematt** [comment]
Your pain boils down to a line like:

“Previous methods often involved complex procedures and significant user interaction to produce useful results.”

--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=

Dr Matthew Wakefield                      
http://bioinf.wehi.edu.au/~wakefield/ <http://bioinf.wehi.edu.au/~wakefield/>
Bioinformatics
Walter and Eliza Hall Institute
1G Royal Parade, Parkville, Vic 3052 Australia
matthew.wakefield@wehi.edu.au <mailto:matthew.wakefield@wehi.edu.au> 

Senior Research Fellow
Life Sciences Computation Centre
Victorian Life Sciences Computation Initiative
University of Melbourne, Parkville Campus
LAB-14, 700 Swanston St, Carlton VIC 3053, Australia
VLSCI, University of Melbourne
matthew.wakefield@unimelb.edu.au <mailto:matthew.wakefield@unimelb.edu.au>

Office Phone: +61 3 9345 2631     Mobile: +61 402 916 018
Skype Video: mjwakefield              GoogleTalk: MattJWakefield
Twitter & Github @genomematt     orcid.org/0000-0001-6624-4698 <http://orcid.org/0000-0001-6624-4698>

--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=

The information contained in this e-mail is confidential and is intended
solely for the addressee. If you are not the named addressee, you must not
disclose or use in any way the information in the e-mail. If you have
received this e-mail by mistake, please notify the sender immediately by
reply e-mail and delete this e-mail and destroy any printed copy.

> On 9 Jul 2015, at 10:57 am, fjrossello <notifications@github.com> wrote:
> 
> The method I used for my
> paper is super slow but I am getting there.


______________________________________________________________________
The information in this email is confidential and intended solely for the addressee.
You must not disclose, forward, print or use it without the permission of the sender.
______________________________________________________________________
